/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.DaoPessoa;
import Model.Filter;
import Model.HibernateDao;
import Model.Operator;
import entities.Pessoa;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willian
 */
public class AtualizaPessoa extends javax.swing.JFrame {

    private Visao telaAnterior;
    private HibernateDao hibernatedao = new HibernateDao();
    private DaoPessoa daoPessoa = new DaoPessoa();
    private Pessoa pessoa;

    /**
     * Creates new form AtualizaPessoa
     */
    public AtualizaPessoa() {
        initComponents();
    }

    public AtualizaPessoa(Visao telaAnterior) throws Exception {
        this();
        this.telaAnterior = telaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void carregarJTable() throws Exception {
        Pessoa p = new Pessoa();
        String consulta = jTextFieldPesquisa.getText();
        if (jRadioButtoncrianca.isEnabled()) {
            Filter f = new Filter("nome", Operator.LIKE, consulta);
            List lista = null;
            try {
                lista = daoPessoa.list(f);
                for (Object e : lista) {
                }
            } catch (Exception ex) {
                Logger.getLogger(AtualizaPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (Object e : lista) {
                DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
                modelo.addColumn("Número do Cadastro");
                modelo.addColumn("Nome da Criança");
                modelo.addColumn("Nome da Mãe");
                modelo.addColumn("Nome do Pai");
                modelo.addColumn("Nome do Bairro que Residi");
                modelo.addColumn("Instituição Pretendida");
                
                if (lista.isEmpty()) {
                    modelo.addRow(new String[]{"Não tem produto",
                        null,
                        null,
                        null,
                        null,
                        null});
                }

                for (int i = 0; i < lista.size(); i++) {
                    p = (Pessoa) lista.get(i);
                    //System.out.println(p.toString());


                    // Alimenta as linhas de dados  
                    modelo.addRow(new String[]{p.getCadastro() + "",                        
                        p.getNome(),
                        p.getNomedaMae(),
                        p.getNomedoPai(),
                        p.getBairro(),
                        p.getInstituicaoPretendida()});
                }

                jTable1.setModel(modelo);
            }
        }if (jRadioButtonmae.isEnabled()) {
            Filter f = new Filter("nomedaMae", Operator.LIKE, consulta);
            List lista = null;
            try {
                lista = daoPessoa.list(f);
                for (Object e : lista) {
                }
            } catch (Exception ex) {
                Logger.getLogger(AtualizaPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (Object e : lista) {
                DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
                modelo.addColumn("Número do Cadastro");
                modelo.addColumn("Nome da Criança");
                modelo.addColumn("Nome da Mãe");
                modelo.addColumn("Nome do Pai");
                modelo.addColumn("Nome do Bairro que Residi");
                modelo.addColumn("Instituição Pretendida");
                
                if (lista.isEmpty()) {
                    modelo.addRow(new String[]{"Não tem produto",
                        null,
                        null,
                        null,
                        null,
                        null});
                }

                for (int i = 0; i < lista.size(); i++) {
                    p = (Pessoa) lista.get(i);
                    //System.out.println(p.toString());


                    // Alimenta as linhas de dados  
                    modelo.addRow(new String[]{p.getCadastro() + "",                        
                        p.getNome(),
                        p.getNomedaMae(),
                        p.getNomedoPai(),
                        p.getBairro(),
                        p.getInstituicaoPretendida()});
                }

                jTable1.setModel(modelo);
            }
        }if (jRadioButtonpai.isEnabled()) {
            Filter f = new Filter("nomedoPai", Operator.LIKE, consulta);
            List lista = null;
            try {
                lista = daoPessoa.list(f);
                for (Object e : lista) {
                }
            } catch (Exception ex) {
                Logger.getLogger(AtualizaPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (Object e : lista) {
                DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
                modelo.addColumn("Número do Cadastro");
                modelo.addColumn("Nome da Criança");
                modelo.addColumn("Nome da Mãe");
                modelo.addColumn("Nome do Pai");
                modelo.addColumn("Nome do Bairro que Residi");
                modelo.addColumn("Instituição Pretendida");
                
                if (lista.isEmpty()) {
                    modelo.addRow(new String[]{"Não tem pessoa",
                        null,
                        null,
                        null,
                        null,
                        null});
                }

                for (int i = 0; i < lista.size(); i++) {
                    p = (Pessoa) lista.get(i);
                    //System.out.println(p.toString());


                    // Alimenta as linhas de dados  
                    modelo.addRow(new String[]{p.getCadastro() + "",                        
                        p.getNome(),
                        p.getNomedaMae(),
                        p.getNomedoPai(),
                        p.getBairro(),
                        p.getInstituicaoPretendida()});
                }

                jTable1.setModel(modelo);
            }
        }if(jRadioNumerodoCadastro.isEnabled()){
            Filter f = new Filter("cadastro", Operator.LIKE, consulta);
            List lista = null;
            try {
                lista = daoPessoa.list(f);
                for (Object e : lista) {
                }
            } catch (Exception ex) {
                Logger.getLogger(AtualizaPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (Object e : lista) {
                DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
                modelo.addColumn("Número do Cadastro");
                modelo.addColumn("Nome da Criança");
                modelo.addColumn("Nome da Mãe");
                modelo.addColumn("Nome do Pai");
                modelo.addColumn("Nome do Bairro que Residi");
                modelo.addColumn("Instituição Pretendida");
                
                if (lista.isEmpty()) {
                    modelo.addRow(new String[]{"Não tem pessoa",
                        null,
                        null,
                        null,
                        null,
                        null});
                }

                for (int i = 0; i < lista.size(); i++) {
                    p = (Pessoa) lista.get(i);
                    //System.out.println(p.toString());


                    // Alimenta as linhas de dados  
                    modelo.addRow(new String[]{p.getCadastro() + "",                        
                        p.getNome(),
                        p.getNomedaMae(),
                        p.getNomedoPai(),
                        p.getBairro(),
                        p.getInstituicaoPretendida()});
                }

                jTable1.setModel(modelo);
            }
        }
        
    }
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jRadioButtoncrianca = new javax.swing.JRadioButton();
        jRadioButtonmae = new javax.swing.JRadioButton();
        jRadioButtonpai = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jRadioNumerodoCadastro = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 550));

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtoncrianca);
        jRadioButtoncrianca.setSelected(true);
        jRadioButtoncrianca.setText("nome da Criança");

        buttonGroup1.add(jRadioButtonmae);
        jRadioButtonmae.setText("nome da mãe");
        jRadioButtonmae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmaeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonpai);
        jRadioButtonpai.setText("nome do pai");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioNumerodoCadastro);
        jRadioNumerodoCadastro.setText("número do cadastro");
        jRadioNumerodoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNumerodoCadastroActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/inconi de campo mourao.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconi secretaria da educação.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel3.setText("Município de Campo Mourão");

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel4.setText("SECRETARIA DA EDUCAÇÃO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtoncrianca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonmae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonpai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioNumerodoCadastro)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisar)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonExcluir)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonVoltar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonpai)
                    .addComponent(jRadioButtonmae)
                    .addComponent(jRadioButtoncrianca)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jRadioNumerodoCadastro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonVoltar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jRadioButtonmaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonmaeActionPerformed

    private void jRadioNumerodoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNumerodoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioNumerodoCadastroActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            int linha = jTable1.getSelectedRow();

            Pessoa p = daoPessoa.list().get(linha);
            System.out.println(p.toString());

//            this.setEnabled(false);
            jButtonExcluir.setEnabled(true);
            Object[] options = {"OK",
                "Cancel"};
            int n = JOptionPane.showOptionDialog(this,
                    "Deseja Realmente Excluir "
                    + p.getNome() + " ?", "Excluir",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);
            if (n == JOptionPane.YES_OPTION) {
                daoPessoa.delete(p);
                atualizarModelo();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione uma pessoa!");
            jButtonExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            int linha = jTable1.getSelectedRow();
            
            Pessoa p = daoPessoa.list().get(linha);
            System.out.println(p.toString());

//            this.setEnabled(false);
            jButtonEditar.setEnabled(true);
            new Cadastro(this, p).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione uma pessoa!");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        try {
            carregarJTable();
        } catch (Exception ex) {
            Logger.getLogger(AtualizaPessoa.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        System.out.println("form window activated");
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.telaAnterior.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizaPessoa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtoncrianca;
    private javax.swing.JRadioButton jRadioButtonmae;
    private javax.swing.JRadioButton jRadioButtonpai;
    private javax.swing.JRadioButton jRadioNumerodoCadastro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables

    public void atualizarModelo() throws Exception {

        System.out.println("atualizando modelo...");
        carregarJTable();
    }
}
