/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.DaoPessoa;
import Model.HibernateDao;
import entities.Pessoa;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
    
/**
 *
 * @author willian
 */
public class Cadastro extends javax.swing.JDialog {
    private Visao telaAnterior;
    private Pessoa pessoa;
    private Pesquisa pesquisa;
    private HibernateDao hibernatedao = new HibernateDao();
    /**
     * Creates new form Cadastro
     */
    private Cadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Cadastro(Visao telaAnterior) {
        this();
        this.telaAnterior = telaAnterior;
    }

    public Cadastro(Pesquisa atualizarProduto, Pessoa p) {
        this();

        this.pesquisa = atualizarProduto;
        this.pessoa = p;
    }
    public Cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldnumerodocadastro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFielddatadenascimentodacrianca = new javax.swing.JFormattedTextField();
        jTextFieldnomedacrianca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldidadeano = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldidademeses = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioberçario = new javax.swing.JRadioButton();
        jRadioButtonmaternal1 = new javax.swing.JRadioButton();
        jRadioButtonMaternal2 = new javax.swing.JRadioButton();
        jRadioButtonNivel1 = new javax.swing.JRadioButton();
        jRadioButtonNivel2 = new javax.swing.JRadioButton();
        jRadioButtonNivel3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldInstituicaoPretendida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNomedaMae = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonMaeTrabalhaS = new javax.swing.JRadioButton();
        jRadioButtonMaeTrabalhaN = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldProfissaodaMae = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldLocaldeTrabalhodaMae = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTelefonedaMãe = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNomedoPai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jRadioButtonPaiTrabalhaS = new javax.swing.JRadioButton();
        jRadioButtonPaiTrabalhaN = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldProfissaodoPai = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldLocaldeTrabalhodoPai = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldTelefonedoPai = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jRadioButtonEstadoCivilCasado = new javax.swing.JRadioButton();
        jRadioButtonEstadoCivilSeparado = new javax.swing.JRadioButton();
        jRadioButtonEstadoCivilSolteiro = new javax.swing.JRadioButton();
        jRadioButtonViuvo = new javax.swing.JRadioButton();
        jRadioButtonEstadoCivilOutros = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldRendaFamiliar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldTelefoneResidencial = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldAcriancaFicaaosCuidadodeQuem = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldEncaminhadaDia = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldInstituicao = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOBS = new javax.swing.JTextArea();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cadastro Nº:");

        jTextFieldnumerodocadastro.setToolTipText("Número do cadastro");
        jTextFieldnumerodocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumerodocadastroActionPerformed(evt);
            }
        });
        jTextFieldnumerodocadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnumerodocadastroKeyTyped(evt);
            }
        });

        jLabel2.setText("Nome da Criança:");

        jLabel3.setText("Nascida:");

        jFormattedTextFielddatadenascimentodacrianca.setText("     /       /");
        jFormattedTextFielddatadenascimentodacrianca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFielddatadenascimentodacriancaActionPerformed(evt);
            }
        });
        jFormattedTextFielddatadenascimentodacrianca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFielddatadenascimentodacriancaKeyTyped(evt);
            }
        });

        jTextFieldnomedacrianca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnomedacriancaKeyTyped(evt);
            }
        });

        jLabel4.setText("Idade:");

        jTextFieldidadeano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidadeanoActionPerformed(evt);
            }
        });
        jTextFieldidadeano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldidadeanoKeyTyped(evt);
            }
        });

        jLabel5.setText("anos");

        jTextFieldidademeses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldidademesesKeyTyped(evt);
            }
        });

        jLabel6.setText("meses");

        buttonGroup1.add(jRadioberçario);
        jRadioberçario.setText("Berçário");

        buttonGroup1.add(jRadioButtonmaternal1);
        jRadioButtonmaternal1.setText("Maternal I");

        buttonGroup1.add(jRadioButtonMaternal2);
        jRadioButtonMaternal2.setText("Maternal II");

        buttonGroup1.add(jRadioButtonNivel1);
        jRadioButtonNivel1.setText("Nível I");

        buttonGroup1.add(jRadioButtonNivel2);
        jRadioButtonNivel2.setText("Nível II");

        buttonGroup1.add(jRadioButtonNivel3);
        jRadioButtonNivel3.setText("Nível III");

        jLabel7.setText("Instituição pretendida:");

        jTextFieldInstituicaoPretendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstituicaoPretendidaActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome da Mãe:");

        jTextFieldNomedaMae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomedaMaeKeyTyped(evt);
            }
        });

        jLabel9.setText("Mãe Trabalha:");

        buttonGroup2.add(jRadioButtonMaeTrabalhaS);
        jRadioButtonMaeTrabalhaS.setText("Sim");

        buttonGroup2.add(jRadioButtonMaeTrabalhaN);
        jRadioButtonMaeTrabalhaN.setText("Não");

        jLabel10.setText("Profissão da Mãe:");

        jLabel11.setText("Local de Trabalho:");

        jTextFieldLocaldeTrabalhodaMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLocaldeTrabalhodaMaeActionPerformed(evt);
            }
        });

        jLabel12.setText("Telefone:");

        jTextFieldTelefonedaMãe.setToolTipText("Telefone do local de trabalho da mãe");
        jTextFieldTelefonedaMãe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonedaMãeKeyTyped(evt);
            }
        });

        jLabel13.setText("Nome do Pai:");

        jTextFieldNomedoPai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomedoPaiKeyTyped(evt);
            }
        });

        jLabel14.setText("Pai Trabalha:");

        buttonGroup3.add(jRadioButtonPaiTrabalhaS);
        jRadioButtonPaiTrabalhaS.setText("Sim");

        buttonGroup3.add(jRadioButtonPaiTrabalhaN);
        jRadioButtonPaiTrabalhaN.setText("Não");

        jLabel15.setText("Profissão do Pai:");

        jLabel16.setText("Local de Trabalho: ");

        jLabel17.setText("Telefone:");

        jTextFieldTelefonedoPai.setToolTipText("Telefone do local de trabalho do pai");
        jTextFieldTelefonedoPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonedoPaiActionPerformed(evt);
            }
        });
        jTextFieldTelefonedoPai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonedoPaiKeyTyped(evt);
            }
        });

        jLabel18.setText("Estado Civil:");

        buttonGroup4.add(jRadioButtonEstadoCivilCasado);
        jRadioButtonEstadoCivilCasado.setText("Casados");

        buttonGroup4.add(jRadioButtonEstadoCivilSeparado);
        jRadioButtonEstadoCivilSeparado.setText("Separados");

        buttonGroup4.add(jRadioButtonEstadoCivilSolteiro);
        jRadioButtonEstadoCivilSolteiro.setText("Solteiros");

        buttonGroup4.add(jRadioButtonViuvo);
        jRadioButtonViuvo.setText("Viuvo (a)");

        buttonGroup4.add(jRadioButtonEstadoCivilOutros);
        jRadioButtonEstadoCivilOutros.setText("Outros");

        jLabel19.setText("Renda Familiar:");

        jLabel20.setText("R$");

        jTextFieldRendaFamiliar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRendaFamiliarKeyTyped(evt);
            }
        });

        jLabel21.setText("Endereço Residencial:");

        jLabel22.setText("Rua:");

        jTextFieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRuaActionPerformed(evt);
            }
        });

        jLabel23.setText("Nº:");

        jTextFieldNumero.setToolTipText("Número da casa");
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });

        jLabel24.setText("CEP:");

        jTextFieldCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCEPKeyTyped(evt);
            }
        });

        jLabel25.setText("Bairro:");

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jLabel26.setText("Telefone:");

        jTextFieldTelefoneResidencial.setToolTipText("telefone para contato");
        jTextFieldTelefoneResidencial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefoneResidencialKeyTyped(evt);
            }
        });

        jLabel27.setText("Obs: A criança fica aos cuidados de quem?");

        jTextFieldAcriancaFicaaosCuidadodeQuem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAcriancaFicaaosCuidadodeQuemActionPerformed(evt);
            }
        });

        jLabel28.setText("Encaminhada dia:");

        jTextFieldEncaminhadaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEncaminhadaDiaActionPerformed(evt);
            }
        });

        jLabel29.setText("Instituição:");

        jTextFieldInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstituicaoActionPerformed(evt);
            }
        });

        jLabel30.setText("OBS:");

        jTextAreaOBS.setColumns(20);
        jTextAreaOBS.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOBS);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioberçario)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButtonmaternal1)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButtonMaternal2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFielddatadenascimentodacrianca, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldidadeano, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldidademeses, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButtonNivel1)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButtonNivel2)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButtonNivel3))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEncaminhadaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldInstituicao))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAcriancaFicaaosCuidadodeQuem))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonEstadoCivilCasado)
                                        .addGap(26, 26, 26)
                                        .addComponent(jRadioButtonEstadoCivilSeparado)
                                        .addGap(26, 26, 26)
                                        .addComponent(jRadioButtonEstadoCivilSolteiro)
                                        .addGap(26, 26, 26)
                                        .addComponent(jRadioButtonViuvo)
                                        .addGap(26, 26, 26)
                                        .addComponent(jRadioButtonEstadoCivilOutros))
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(36, 36, 36)
                                                .addComponent(jTextFieldnomedacrianca, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldInstituicaoPretendida, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(15, 15, 15)
                                                        .addComponent(jTextFieldNomedaMae))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jTextFieldNomedoPai)
                                                            .addComponent(jTextFieldProfissaodaMae)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jTextFieldLocaldeTrabalhodaMae, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel12)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldTelefonedaMãe, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jRadioButtonPaiTrabalhaS)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jRadioButtonPaiTrabalhaN))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jRadioButtonMaeTrabalhaS)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jRadioButtonMaeTrabalhaN)))
                                                        .addGap(0, 0, Short.MAX_VALUE)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(609, 609, 609)))
                                    .addComponent(jLabel13)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldProfissaodoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldLocaldeTrabalhodoPai)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldTelefonedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextFieldRendaFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldnumerodocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(569, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldnumerodocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldnomedacrianca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFielddatadenascimentodacrianca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldidadeano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldidademeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioberçario)
                    .addComponent(jRadioButtonmaternal1)
                    .addComponent(jRadioButtonMaternal2)
                    .addComponent(jRadioButtonNivel1)
                    .addComponent(jRadioButtonNivel2)
                    .addComponent(jRadioButtonNivel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldInstituicaoPretendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNomedaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButtonMaeTrabalhaS)
                    .addComponent(jRadioButtonMaeTrabalhaN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldProfissaodaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldLocaldeTrabalhodaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldTelefonedaMãe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldNomedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jRadioButtonPaiTrabalhaS)
                    .addComponent(jRadioButtonPaiTrabalhaN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldProfissaodoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldLocaldeTrabalhodoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jTextFieldTelefonedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jRadioButtonEstadoCivilCasado)
                    .addComponent(jRadioButtonEstadoCivilSeparado)
                    .addComponent(jRadioButtonEstadoCivilSolteiro)
                    .addComponent(jRadioButtonViuvo)
                    .addComponent(jRadioButtonEstadoCivilOutros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldRendaFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldAcriancaFicaaosCuidadodeQuem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldEncaminhadaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnumerodocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumerodocadastroActionPerformed
       
    }//GEN-LAST:event_jTextFieldnumerodocadastroActionPerformed

    private void jTextFieldidadeanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidadeanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidadeanoActionPerformed

    private void jTextFieldInstituicaoPretendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstituicaoPretendidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstituicaoPretendidaActionPerformed

    private void jTextFieldLocaldeTrabalhodaMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLocaldeTrabalhodaMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLocaldeTrabalhodaMaeActionPerformed

    private void jTextFieldTelefonedoPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonedoPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonedoPaiActionPerformed

    private void jTextFieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRuaActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jTextFieldAcriancaFicaaosCuidadodeQuemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAcriancaFicaaosCuidadodeQuemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAcriancaFicaaosCuidadodeQuemActionPerformed

    private void jTextFieldEncaminhadaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEncaminhadaDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEncaminhadaDiaActionPerformed

    private void jTextFieldInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstituicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstituicaoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        System.out.println("Salvar aqui");
        Pessoa p = new Pessoa();
        DaoPessoa daoPessoa = new DaoPessoa();

        
        int cadastro = Integer.getInteger(jTextFieldnumerodocadastro.getText());
        String nome = jTextFieldnomedacrianca.getText();
        String dataNascimento = jFormattedTextFielddatadenascimentodacrianca.getText();
        int idadeAno = Integer.getInteger(jTextFieldidadeano.getText());
        int idadeMes = Integer.getInteger(jTextFieldidademeses.getText());
        // os jbooton aqui do nivel que ele é
        String instituicaoPretendida = jTextFieldInstituicaoPretendida.getText();
        
        String nomedaMae = jTextFieldNomedaMae.getText();
        // j boton se mae trabalha ou nao
        String profisaodaMae = jTextFieldProfissaodaMae.getText();
        String localdeTrabalhodaMae = jTextFieldLocaldeTrabalhodaMae.getText();
        String telefonedaMae = jTextFieldTelefonedaMãe.getText();
        
        String nomedoPai = jTextFieldNomedoPai.getText();
        // jboton aqui se o pai trabalha ou nao
        String profisaodoPai = jTextFieldNomedoPai.getText();
        String localdeTrabalhodoPai = jTextFieldProfissaodoPai.getText();
        String telefonedoPai = jTextFieldTelefonedoPai.getText();
        
        //estado civil que usa o jboton
        float rendaFamiliar = Float.parseFloat(jTextFieldRendaFamiliar.getText());
        String rua = jTextFieldRua.getText();
        int numerodaCasa = Integer.getInteger(jTextFieldNumero.getText());
        String cep = jTextFieldCEP.getText();
        String bairro = jTextFieldBairro.getText();
        String quemCuidadaCrianca = jTextFieldAcriancaFicaaosCuidadodeQuem.getText();
        String encamiada = jTextFieldEncaminhadaDia.getText();
        String istituicao = jTextFieldInstituicao.getText();
        String obs = jTextAreaOBS.getText();
        
        p.setCadastro(cadastro);
        p.setNome(nome);
        p.setDatadeNascimento(dataNascimento);
        p.setAnosdeNascimento(idadeAno);
        p.setMesdeNascimento(idadeMes);
        p.setInstituicaoPretendida(instituicaoPretendida);
        p.setNomedaMae(nomedaMae);
        // faltando se mae trabalha aqui
        p.setProfissaodaMae(profisaodaMae);
        p.setLocaldeTrabalhodaMae(localdeTrabalhodaMae);
        p.setTelefonedaMae(telefonedaMae);
        p.setNomedoPai(nomedoPai);
        // faltando se o pai trabalha aqui
        p.setProfissaodoPai(profisaodoPai);
        p.setLocaldeTrabalhodoPai(localdeTrabalhodoPai);
        p.setTelefonedoPai(telefonedoPai);
        //faltando o estado civil aqui
        p.setRendaFamiliar(rendaFamiliar);
        p.setRua(rua);
        p.setNumero(numerodaCasa);
        p.setCEP(cep);
        p.setBairro(bairro);
        p.setCuidaCrianca(quemCuidadaCrianca);
        p.setEncaminhamento(encamiada);
        p.setInstituicao(istituicao);
        
        try {
            daoPessoa.persist(p);
            JOptionPane.showMessageDialog(this, "Cadastro realizado com Sucesso");
            
            } catch (Exception ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldnumerodocadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumerodocadastroKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldnumerodocadastroKeyTyped

    private void jTextFieldnomedacriancaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnomedacriancaKeyTyped
       String caracteres = "qwertyuiopasdfghjklçzxcvbnmQWERTYUIOPASDFGHJKLÇZXCVBNM";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldnomedacriancaKeyTyped

    private void jFormattedTextFielddatadenascimentodacriancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFielddatadenascimentodacriancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFielddatadenascimentodacriancaActionPerformed

    private void jFormattedTextFielddatadenascimentodacriancaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFielddatadenascimentodacriancaKeyTyped
        String caracteres = "0987654321/";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextFielddatadenascimentodacriancaKeyTyped

    private void jTextFieldidadeanoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldidadeanoKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldidadeanoKeyTyped

    private void jTextFieldidademesesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldidademesesKeyTyped
        String caracteres = "0987654321/";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldidademesesKeyTyped

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jTextFieldTelefonedaMãeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonedaMãeKeyTyped
        String caracteres = "0987654321()-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefonedaMãeKeyTyped

    private void jTextFieldTelefonedoPaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonedoPaiKeyTyped
       String caracteres = "0987654321()-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefonedoPaiKeyTyped

    private void jTextFieldTelefoneResidencialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneResidencialKeyTyped
       String caracteres = "0987654321()-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefoneResidencialKeyTyped

    private void jTextFieldRendaFamiliarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRendaFamiliarKeyTyped
        String caracteres = "0987654321.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRendaFamiliarKeyTyped

    private void jTextFieldCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCEPKeyTyped
        String caracteres = "0987654321.-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCEPKeyTyped

    private void jTextFieldNomedaMaeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomedaMaeKeyTyped
       String caracteres = "qwertyuiopasdfghjklçzxcvbnmQWERTYUIOPASDFGHJKLÇZXCVBNM";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomedaMaeKeyTyped

    private void jTextFieldNomedoPaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomedoPaiKeyTyped
       String caracteres = "qwertyuiopasdfghjklçzxcvbnmQWERTYUIOPASDFGHJKLÇZXCVBNM";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomedoPaiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro dialog = new Cadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFielddatadenascimentodacrianca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonEstadoCivilCasado;
    private javax.swing.JRadioButton jRadioButtonEstadoCivilOutros;
    private javax.swing.JRadioButton jRadioButtonEstadoCivilSeparado;
    private javax.swing.JRadioButton jRadioButtonEstadoCivilSolteiro;
    private javax.swing.JRadioButton jRadioButtonMaeTrabalhaN;
    private javax.swing.JRadioButton jRadioButtonMaeTrabalhaS;
    private javax.swing.JRadioButton jRadioButtonMaternal2;
    private javax.swing.JRadioButton jRadioButtonNivel1;
    private javax.swing.JRadioButton jRadioButtonNivel2;
    private javax.swing.JRadioButton jRadioButtonNivel3;
    private javax.swing.JRadioButton jRadioButtonPaiTrabalhaN;
    private javax.swing.JRadioButton jRadioButtonPaiTrabalhaS;
    private javax.swing.JRadioButton jRadioButtonViuvo;
    private javax.swing.JRadioButton jRadioButtonmaternal1;
    private javax.swing.JRadioButton jRadioberçario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextAreaOBS;
    private javax.swing.JTextField jTextFieldAcriancaFicaaosCuidadodeQuem;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldEncaminhadaDia;
    private javax.swing.JTextField jTextFieldInstituicao;
    private javax.swing.JTextField jTextFieldInstituicaoPretendida;
    private javax.swing.JTextField jTextFieldLocaldeTrabalhodaMae;
    private javax.swing.JTextField jTextFieldLocaldeTrabalhodoPai;
    private javax.swing.JTextField jTextFieldNomedaMae;
    private javax.swing.JTextField jTextFieldNomedoPai;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldProfissaodaMae;
    private javax.swing.JTextField jTextFieldProfissaodoPai;
    private javax.swing.JTextField jTextFieldRendaFamiliar;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldTelefoneResidencial;
    private javax.swing.JTextField jTextFieldTelefonedaMãe;
    private javax.swing.JTextField jTextFieldTelefonedoPai;
    private javax.swing.JTextField jTextFieldidadeano;
    private javax.swing.JTextField jTextFieldidademeses;
    private javax.swing.JTextField jTextFieldnomedacrianca;
    private javax.swing.JTextField jTextFieldnumerodocadastro;
    // End of variables declaration//GEN-END:variables
private void carregarPessoaNosCampos() {
    
}
}
