/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Control.ControlePessoa;
import Model.HibernateDao;
import entities.Pessoa;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author willian
 */
public class Cadastro extends javax.swing.JDialog {

    private Visao telaAnterior;
    private Pessoa pessoa;
    private AtualizaPessoa atualizaPessoa;
    private HibernateDao hibernatedao = new HibernateDao();

    /**
     * Creates new form Cadastro
     */
    private Cadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Cadastro(Visao telaAnterior) {
        this();
        this.telaAnterior = telaAnterior;
    }

    public Cadastro(AtualizaPessoa atualizaPessoa, Pessoa p) {
        this();

        this.atualizaPessoa = atualizaPessoa;
        this.pessoa = p;
    }

    public Cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldnumerodocadastro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFielddatadenascimentodacrianca = new javax.swing.JFormattedTextField();
        jTextFieldnomedacrianca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldidadeano = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldidademeses = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldInstituicaoPretendida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNomedaMae = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldProfissaodaMae = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTelefonedaMãe = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNomedoPai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldProfissaodoPai = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldTelefonedoPai = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldRendaFamiliar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldTelefoneResidencial = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldAcriancaFicaaosCuidadodeQuem = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldEncaminhadaDia = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldInstituicao = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOBS = new javax.swing.JTextArea();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxPaiTrabalha = new javax.swing.JComboBox();
        jComboBoxMaeTrabalha = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jComboBoxNivelEscolar = new javax.swing.JComboBox();
        jTextFieldLocaldeTrabalhodoPai = new javax.swing.JTextField();
        jTextFieldLocaldeTrabalhodaMae = new javax.swing.JTextField();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Cadastro Nº:");

        jTextFieldnumerodocadastro.setToolTipText("Número do cadastro");
        jTextFieldnumerodocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumerodocadastroActionPerformed(evt);
            }
        });
        jTextFieldnumerodocadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnumerodocadastroKeyTyped(evt);
            }
        });

        jLabel2.setText("Nome da Criança:");

        jLabel3.setText("Nascida:");

        jFormattedTextFielddatadenascimentodacrianca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFielddatadenascimentodacriancaActionPerformed(evt);
            }
        });
        jFormattedTextFielddatadenascimentodacrianca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFielddatadenascimentodacriancaKeyTyped(evt);
            }
        });

        jTextFieldnomedacrianca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnomedacriancaKeyTyped(evt);
            }
        });

        jLabel4.setText("Idade:");

        jTextFieldidadeano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidadeanoActionPerformed(evt);
            }
        });
        jTextFieldidadeano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldidadeanoKeyTyped(evt);
            }
        });

        jLabel5.setText("anos");

        jTextFieldidademeses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldidademesesKeyTyped(evt);
            }
        });

        jLabel6.setText("meses");

        jLabel7.setText("Instituição pretendida:");

        jTextFieldInstituicaoPretendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstituicaoPretendidaActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome da Mãe:");

        jTextFieldNomedaMae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomedaMaeKeyTyped(evt);
            }
        });

        jLabel9.setText("Mãe Trabalha:");

        jLabel10.setText("Profissão da Mãe:");

        jLabel11.setText("Local de Trabalho:");

        jLabel12.setText("Telefone:");

        jTextFieldTelefonedaMãe.setToolTipText("Telefone do local de trabalho da mãe");
        jTextFieldTelefonedaMãe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonedaMãeKeyTyped(evt);
            }
        });

        jLabel13.setText("Nome do Pai:");

        jTextFieldNomedoPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomedoPaiActionPerformed(evt);
            }
        });
        jTextFieldNomedoPai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomedoPaiKeyTyped(evt);
            }
        });

        jLabel14.setText("Pai Trabalha:");

        jLabel15.setText("Profissão do Pai:");

        jLabel16.setText("Local de Trabalho: ");

        jLabel17.setText("Telefone:");

        jTextFieldTelefonedoPai.setToolTipText("Telefone do local de trabalho do pai");
        jTextFieldTelefonedoPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonedoPaiActionPerformed(evt);
            }
        });
        jTextFieldTelefonedoPai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonedoPaiKeyTyped(evt);
            }
        });

        jLabel18.setText("Estado Civil:");

        jLabel19.setText("Renda Familiar:");

        jLabel20.setText("R$");

        jTextFieldRendaFamiliar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRendaFamiliarKeyTyped(evt);
            }
        });

        jLabel21.setText("Endereço Residencial:");

        jLabel22.setText("Rua:");

        jTextFieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRuaActionPerformed(evt);
            }
        });

        jLabel23.setText("Nº:");

        jTextFieldNumero.setToolTipText("Número da casa");
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });

        jLabel24.setText("CEP:");

        jTextFieldCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCEPKeyTyped(evt);
            }
        });

        jLabel25.setText("Bairro:");

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jLabel26.setText("Telefone:");

        jTextFieldTelefoneResidencial.setToolTipText("telefone para contato");
        jTextFieldTelefoneResidencial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefoneResidencialKeyTyped(evt);
            }
        });

        jLabel27.setText("Obs: A criança fica aos cuidados de quem?");

        jTextFieldAcriancaFicaaosCuidadodeQuem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAcriancaFicaaosCuidadodeQuemActionPerformed(evt);
            }
        });

        jLabel28.setText("Encaminhada dia:");

        jTextFieldEncaminhadaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEncaminhadaDiaActionPerformed(evt);
            }
        });

        jLabel29.setText("Instituição:");

        jTextFieldInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstituicaoActionPerformed(evt);
            }
        });

        jLabel30.setText("OBS:");

        jTextAreaOBS.setColumns(20);
        jTextAreaOBS.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOBS);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxPaiTrabalha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));
        jComboBoxPaiTrabalha.setToolTipText("O pai trabalha?");

        jComboBoxMaeTrabalha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));
        jComboBoxMaeTrabalha.setToolTipText("A mãe trabalha ?");
        jComboBoxMaeTrabalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaeTrabalhaActionPerformed(evt);
            }
        });

        jLabel31.setText("Nível da criança:");

        jComboBoxNivelEscolar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Berçário", "Maternal I", "Maternal II", "Nível I", "Nível II", "Nível III" }));
        jComboBoxNivelEscolar.setToolTipText("Nivel escolar da criança");

        jTextFieldLocaldeTrabalhodoPai.setToolTipText("Local onde o pai trabalha");

        jTextFieldLocaldeTrabalhodaMae.setToolTipText("Local onde a mãe trabalha");

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casados", "Separados", "Solteiros", "Viuvo(a)", "Outros" }));
        jComboBoxEstadoCivil.setToolTipText("Estado civil dos pais");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jFormattedTextFielddatadenascimentodacrianca, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldidadeano, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldidademeses, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addGap(326, 326, 326))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(56, 56, 56)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jComboBoxPaiTrabalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(535, 535, 535))
                                        .addComponent(jTextFieldNomedoPai)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(14, 14, 14))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(25, 25, 25)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldProfissaodoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldLocaldeTrabalhodoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldTelefonedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(6, 6, 6)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel11))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxMaeTrabalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldLocaldeTrabalhodaMae, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldTelefonedaMãe, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                        .addComponent(jTextFieldProfissaodaMae)
                                        .addComponent(jTextFieldNomedaMae)))
                                .addComponent(jLabel14)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel18))
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldRendaFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonCancelar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel28)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldEncaminhadaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldInstituicao))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldAcriancaFicaaosCuidadodeQuem))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel24)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2)
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(2, 2, 2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel31))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jComboBoxNivelEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 497, Short.MAX_VALUE))
                                                .addComponent(jTextFieldInstituicaoPretendida)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(36, 36, 36)
                                            .addComponent(jTextFieldnomedacrianca, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(9, 9, 9)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldnumerodocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(665, 665, 665))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldnumerodocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldnomedacrianca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFielddatadenascimentodacrianca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldidadeano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldidademeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jComboBoxNivelEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldInstituicaoPretendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNomedaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxMaeTrabalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldProfissaodaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldTelefonedaMãe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLocaldeTrabalhodaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldNomedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxPaiTrabalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldProfissaodoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldLocaldeTrabalhodoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldTelefonedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldRendaFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldAcriancaFicaaosCuidadodeQuem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldEncaminhadaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonCancelar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMaeTrabalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaeTrabalhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMaeTrabalhaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        System.out.println("Salvar aqui");
        Pessoa p = new Pessoa();
        int id = 0;
        int cadastro = Integer.parseInt(jTextFieldnumerodocadastro.getText());
        String nome = jTextFieldnomedacrianca.getText();
        String dataNascimento = jFormattedTextFielddatadenascimentodacrianca.getText();
        int idadeAno = Integer.parseInt(jTextFieldidadeano.getText());
        int idadeMes = Integer.parseInt(jTextFieldidademeses.getText());
        String nivelescolar = (String) jComboBoxNivelEscolar.getSelectedItem();
        String instituicaoPretendida = jTextFieldInstituicaoPretendida.getText();
        String nomedaMae = jTextFieldNomedaMae.getText();
        int maeTrabalha = jComboBoxMaeTrabalha.getSelectedIndex();
        String profisaodaMae = jTextFieldProfissaodaMae.getText();
        String localdeTrabalhodaMae = jTextFieldLocaldeTrabalhodaMae.getText();
        String telefonedaMae = jTextFieldTelefonedaMãe.getText();
        String nomedoPai = jTextFieldNomedoPai.getText();
        int paiTrabalha = jComboBoxPaiTrabalha.getSelectedIndex();
        String profisaodoPai = jTextFieldProfissaodoPai.getText();
        String localdeTrabalhodoPai = jTextFieldLocaldeTrabalhodoPai.getText();
        String telefonedoPai = jTextFieldTelefonedoPai.getText();
        String estadoCivil = (String) jComboBoxEstadoCivil.getSelectedItem();
        float rendaFamiliar = Float.parseFloat(jTextFieldRendaFamiliar.getText());
        String rua = jTextFieldRua.getText();
        int numerodaCasa = Integer.parseInt(jTextFieldNumero.getText());
        String cep = jTextFieldCEP.getText();
        String bairro = jTextFieldBairro.getText();
        String quemCuidadaCrianca = jTextFieldAcriancaFicaaosCuidadodeQuem.getText();
        String encamiada = jTextFieldEncaminhadaDia.getText();
        String telefonedeContato = jTextFieldTelefoneResidencial.getText();
        String istituicao = jTextFieldInstituicao.getText();
        String obs = jTextAreaOBS.getText();
        
        p = this.pessoa;
        if (p == null) {
            // criar um objeto Produto
            p = new Pessoa(id,
                    rendaFamiliar,
                    quemCuidadaCrianca,
                    encamiada,
                    istituicao,
                    instituicaoPretendida,
                    cadastro,
                    obs,
                    estadoCivil,
                    nomedoPai,
                    paiTrabalha == 0 ? false : true,
                    profisaodoPai,
                    localdeTrabalhodoPai,
                    telefonedoPai,
                    nomedaMae,
                    maeTrabalha == 0 ? false : true,
                    profisaodaMae,
                    localdeTrabalhodaMae,
                    telefonedaMae,
                    nome,
                    dataNascimento,
                    idadeAno,
                    idadeMes,
                    nivelescolar,
                    rua,
                    cep,
                    numerodaCasa,
                    bairro,
                    telefonedeContato);

        } else {
            // atualiza dados do produto
            p.setCadastro(cadastro);
            p.setNome(nome);
            p.setDatadeNascimento(dataNascimento);
            p.setAnosdeNascimento(idadeAno);
            p.setMesdeNascimento(idadeMes);
            p.setInstituicaoPretendida(instituicaoPretendida);
            p.setNivel(nivelescolar);
            p.setNomedaMae(nomedaMae);
            p.setTrabalhodaMae(maeTrabalha == 0 ? true : false);
            p.setProfissaodaMae(profisaodaMae);
            p.setLocaldeTrabalhodaMae(localdeTrabalhodaMae);
            p.setTelefonedaMae(telefonedaMae);
            p.setNomedoPai(nomedoPai);
            p.setTrabalhodoPai(paiTrabalha == 0 ? true : false);
            p.setProfissaodoPai(profisaodoPai);
            p.setLocaldeTrabalhodoPai(localdeTrabalhodoPai);
            p.setTelefonedoPai(telefonedoPai);
            p.setEstadoCivil(estadoCivil);
            p.setRendaFamiliar(rendaFamiliar);
            p.setRua(rua);
            p.setNumero(numerodaCasa);
            p.setCEP(cep);
            p.setBairro(bairro);
            p.setCuidaCrianca(quemCuidadaCrianca);
            p.setEncaminhamento(encamiada);
            p.setInstituicao(istituicao);

        }
        ControlePessoa controlador = new ControlePessoa();
        if (this.pessoa == null) {
            try {
                if (controlador.cadastrarProduto(p)) {
                    JOptionPane.showMessageDialog(this, "Cadastro realizado com Sucesso");
                    jTextFieldnomedacrianca.setText("");
                    jTextFieldnumerodocadastro.setText("");
                    jTextFieldnomedacrianca.setText("");
                    jFormattedTextFielddatadenascimentodacrianca.setText("");
                    jTextFieldidadeano.setText("");
                    jTextFieldidademeses.setText("");
                    jTextFieldInstituicaoPretendida.setText("");
                    jTextFieldNomedaMae.setText("");
                    jTextFieldProfissaodaMae.setText("");
                    jTextFieldLocaldeTrabalhodaMae.setText("");
                    jTextFieldTelefonedaMãe.setText("");
                    jTextFieldNomedoPai.setText("");
                    jTextFieldProfissaodoPai.setText("");
                    jTextFieldLocaldeTrabalhodoPai.setText("");
                    jTextFieldTelefonedoPai.setText("");
                    jTextFieldRendaFamiliar.setText("");
                    jTextFieldRua.setText("");
                    jTextFieldNumero.setText("");
                    jTextFieldCEP.setText("");
                    jTextFieldBairro.setText("");
                    jTextFieldAcriancaFicaaosCuidadodeQuem.setText("");
                    jTextFieldEncaminhadaDia.setText("");
                    jTextFieldInstituicao.setText("");
                    jTextAreaOBS.setText("");
                    jTextFieldTelefoneResidencial.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Cadastro Não realizado. "
                            + "\n\nFaltando dados");
                }
            } catch (Exception ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                if (controlador.atualizarPessoa(p)) {
                    JOptionPane.showMessageDialog(this, "Atualizado com sucesso");
                    if (this.atualizaPessoa != null) {
                        System.out.println("tentando repintar tela");
                        this.atualizaPessoa.atualizarModelo();
                    }
                    this.dispose();
                    this.atualizaPessoa.toFront();
                } else {
                    JOptionPane.showMessageDialog(this, "Atualização Não realizada. "
                            + "\n\nFaltando dados");
                }
            } catch (Exception ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstituicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstituicaoActionPerformed

    private void jTextFieldEncaminhadaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEncaminhadaDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEncaminhadaDiaActionPerformed

    private void jTextFieldAcriancaFicaaosCuidadodeQuemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAcriancaFicaaosCuidadodeQuemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAcriancaFicaaosCuidadodeQuemActionPerformed

    private void jTextFieldTelefoneResidencialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneResidencialKeyTyped
        String caracteres = "0987654321()-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefoneResidencialKeyTyped

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jTextFieldCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCEPKeyTyped
        String caracteres = "0987654321.-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCEPKeyTyped

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jTextFieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRuaActionPerformed

    private void jTextFieldRendaFamiliarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRendaFamiliarKeyTyped
        String caracteres = "0987654321.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRendaFamiliarKeyTyped

    private void jTextFieldTelefonedoPaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonedoPaiKeyTyped
        String caracteres = "0987654321()-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefonedoPaiKeyTyped

    private void jTextFieldTelefonedoPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonedoPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonedoPaiActionPerformed

    private void jTextFieldNomedoPaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomedoPaiKeyTyped
        String caracteres = "ãâáíéqwertyuiopasdfghjklçzxcvbnmÂÃÁÍÉ~^´`QWERTYUIOPASDFGHJKLÇZXCVBNM ";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomedoPaiKeyTyped

    private void jTextFieldTelefonedaMãeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonedaMãeKeyTyped
        String caracteres = "0987654321()-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefonedaMãeKeyTyped

    private void jTextFieldNomedaMaeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomedaMaeKeyTyped
        String caracteres = "ãâáíéqwertyuiopasdfghjklçzxcvbnmÂÃÁÍÉ~^´`QWERTYUIOPASDFGHJKLÇZXCVBNM ";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomedaMaeKeyTyped

    private void jTextFieldInstituicaoPretendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstituicaoPretendidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstituicaoPretendidaActionPerformed

    private void jTextFieldidademesesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldidademesesKeyTyped
        String caracteres = "0987654321/";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldidademesesKeyTyped

    private void jTextFieldidadeanoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldidadeanoKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldidadeanoKeyTyped

    private void jTextFieldidadeanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidadeanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidadeanoActionPerformed

    private void jTextFieldnomedacriancaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnomedacriancaKeyTyped
        String caracteres = "ãâáíéqwertyuiopasdfghjklçzxcvbnmÂÃÁÍÉ~^´`QWERTYUIOPASDFGHJKLÇZXCVBNM ";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldnomedacriancaKeyTyped

    private void jFormattedTextFielddatadenascimentodacriancaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFielddatadenascimentodacriancaKeyTyped
        String caracteres = "0987654321/";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextFielddatadenascimentodacriancaKeyTyped

    private void jFormattedTextFielddatadenascimentodacriancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFielddatadenascimentodacriancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFielddatadenascimentodacriancaActionPerformed

    private void jTextFieldnumerodocadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumerodocadastroKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldnumerodocadastroKeyTyped

    private void jTextFieldnumerodocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumerodocadastroActionPerformed
    }//GEN-LAST:event_jTextFieldnumerodocadastroActionPerformed

    private void jTextFieldNomedoPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomedoPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomedoPaiActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (this.pessoa != null) {
            carregarPessoaNosCampos();
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro dialog = new Cadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxMaeTrabalha;
    private javax.swing.JComboBox jComboBoxNivelEscolar;
    private javax.swing.JComboBox jComboBoxPaiTrabalha;
    private javax.swing.JFormattedTextField jFormattedTextFielddatadenascimentodacrianca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextAreaOBS;
    private javax.swing.JTextField jTextFieldAcriancaFicaaosCuidadodeQuem;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldEncaminhadaDia;
    private javax.swing.JTextField jTextFieldInstituicao;
    private javax.swing.JTextField jTextFieldInstituicaoPretendida;
    private javax.swing.JTextField jTextFieldLocaldeTrabalhodaMae;
    private javax.swing.JTextField jTextFieldLocaldeTrabalhodoPai;
    private javax.swing.JTextField jTextFieldNomedaMae;
    private javax.swing.JTextField jTextFieldNomedoPai;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldProfissaodaMae;
    private javax.swing.JTextField jTextFieldProfissaodoPai;
    private javax.swing.JTextField jTextFieldRendaFamiliar;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldTelefoneResidencial;
    private javax.swing.JTextField jTextFieldTelefonedaMãe;
    private javax.swing.JTextField jTextFieldTelefonedoPai;
    private javax.swing.JTextField jTextFieldidadeano;
    private javax.swing.JTextField jTextFieldidademeses;
    private javax.swing.JTextField jTextFieldnomedacrianca;
    private javax.swing.JTextField jTextFieldnumerodocadastro;
    // End of variables declaration//GEN-END:variables

    private void carregarPessoaNosCampos() {
        jTextFieldnumerodocadastro.setText(this.pessoa.getCadastro() + "");
        jTextFieldnomedacrianca.setText(this.pessoa.getNome());
        jFormattedTextFielddatadenascimentodacrianca.setText(this.pessoa.getDatadeNascimento());
        jTextFieldidadeano.setText(this.pessoa.getAnosdeNascimento() + "");
        jTextFieldidademeses.setText(this.pessoa.getMesdeNascimento() + "");
        // os jbooton aqui do nivel que ele é
        jComboBoxNivelEscolar.setSelectedItem(this.pessoa.getNivel());
        jTextFieldInstituicaoPretendida.setText(this.pessoa.getInstituicaoPretendida());

        jTextFieldNomedaMae.setText(this.pessoa.getNomedaMae());

        jTextFieldProfissaodaMae.setText(this.pessoa.getProfissaodaMae());
        jComboBoxMaeTrabalha.setSelectedIndex(this.pessoa.getTrabalhodaMae() ? 1 : 0);
        jTextFieldLocaldeTrabalhodaMae.setText(this.pessoa.getLocaldeTrabalhodaMae());
        jTextFieldTelefonedaMãe.setText(this.pessoa.getTelefonedaMae());

        jTextFieldNomedoPai.setText(this.pessoa.getNomedoPai());
        // jboton aqui se o pai trabalha ou nao
        jComboBoxPaiTrabalha.setSelectedIndex(this.pessoa.getTrabalhodoPai() ? 1 : 0);
        jTextFieldProfissaodoPai.setText(this.pessoa.getProfissaodoPai());
        jTextFieldLocaldeTrabalhodoPai.setText(this.pessoa.getLocaldeTrabalhodoPai());
        jTextFieldTelefonedoPai.setText(this.pessoa.getTelefonedoPai());

        //estado civil que usa o jboton
        jComboBoxEstadoCivil.setSelectedItem(this.pessoa.getEstadoCivil());
        jTextFieldRendaFamiliar.setText(this.pessoa.getRendaFamiliar() + "");
        jTextFieldRua.setText(this.pessoa.getRua());
        jTextFieldNumero.setText(this.pessoa.getNumero() + "");
        jTextFieldCEP.setText(this.pessoa.getCEP());
        jTextFieldBairro.setText(this.pessoa.getBairro());
        jTextFieldAcriancaFicaaosCuidadodeQuem.setText(this.pessoa.getCuidaCrianca());
        jTextFieldEncaminhadaDia.setText(this.pessoa.getEncaminhamento());
        jTextFieldInstituicao.setText(this.pessoa.getInstituicao());
        jTextAreaOBS.setText(this.pessoa.getOBS());
        jTextFieldTelefoneResidencial.setText(this.pessoa.getTelefonedeContato());
    }
}
